apiVersion: batch/v1
kind: Job
metadata:
  name: profile-db-init
  namespace: snooker
  labels:
    app.kubernetes.io/name: profile-db-init
    app.kubernetes.io/component: job
    app.kubernetes.io/part-of: snooker
  annotations:
    snooker.maiconda.com/extra-points: "4.2 Job for database initialization."
spec:
  backoffLimit: 6 # Se o job falhar, tenta reinstanciar o pod no máximo 6 vezes antes de desistir.
  ttlSecondsAfterFinished: 86400 # Limpa o cluster deletando o Job automaticamente 24h após terminar.
  template:
    metadata:
      labels:
        app.kubernetes.io/name: profile-db-init
        app.kubernetes.io/component: job
        app.kubernetes.io/part-of: snooker
    spec:
      restartPolicy: OnFailure # Se falhar, reinicia. Se der sucesso, finaliza o Job.
      serviceAccountName: snooker-job # Usa a ServiceAccount dedicada a jobs temporários.
      containers:
        - name: profile-db-init
          # Usamos a própria imagem 'postgres:15-alpine' porque ela já possui
          # o cliente do PostgreSQL ('psql', 'createdb', 'pg_dump') instalado por padrão.
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - /scripts/init-profile-db.sh # Executa o script que injetamos via ConfigMap.
          env:
            - name: PROFILE_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: snooker-config
                  key: PROFILE_DB_HOST
            - name: PROFILE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: snooker-config
                  key: PROFILE_DB_NAME
            - name: PROFILE_LEGACY_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: snooker-config
                  key: PROFILE_LEGACY_DB_NAME
            - name: PROFILE_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: snooker-config
                  key: PROFILE_DB_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: snooker-secrets
                  key: PROFILE_DB_PASSWORD
            - name: STORAGE_PUBLIC_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: snooker-config
                  key: STORAGE_PUBLIC_BASE_URL
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
          volumeMounts:
            # Monta o script do ConfigMap na pasta /scripts do container.
            - name: script
              mountPath: /scripts
              readOnly: true
      volumes:
        # Declara o volume do tipo configMap para podermos consumi-lo no container.
        - name: script
          configMap:
            name: profile-db-init-script
