apiVersion: v1
kind: ConfigMap
metadata:
  name: snooker-config
  namespace: snooker
  labels:
    app.kubernetes.io/name: snooker-config
    app.kubernetes.io/part-of: snooker
data:
  PUBLIC_ORIGIN: "http://snooker.local"
  AUTH_ALLOWED_ORIGINS: "http://snooker.local,http://localhost:3000,http://snooker.maiconda.com,https://snooker.maiconda.com,http://snooker.maiconda.com:3000,https://snooker.maiconda.com:3000"
  PROFILE_ALLOWED_ORIGINS: "http://snooker.local,http://localhost:3000,http://snooker.maiconda.com,https://snooker.maiconda.com,http://snooker.maiconda.com:3000,https://snooker.maiconda.com:3000"
  GAME_ALLOWED_ORIGINS: "http://snooker.local,http://localhost:3000,http://snooker.maiconda.com,https://snooker.maiconda.com,http://snooker.maiconda.com:3000,https://snooker.maiconda.com:3000"
  AUTH_COOKIE_SECURE: "false"
  AUTH_DB_HOST: "auth-postgres"
  AUTH_DB_PORT: "5432"
  AUTH_DB_USER: "postgres"
  AUTH_DB_NAME: "snooker_auth"
  PROFILE_DB_HOST: "profile-postgres"
  PROFILE_DB_PORT: "5432"
  PROFILE_DB_USER: "postgres"
  PROFILE_DB_NAME: "snooker_game"
  PROFILE_LEGACY_DB_NAME: "snooker_profile"
  GAME_DB_HOST: "game-postgres"
  GAME_DB_PORT: "5432"
  GAME_DB_USER: "postgres"
  GAME_DB_NAME: "snooker_game"
  DB_SSLMODE: "disable"
  AUTH_INTERNAL_URL: "http://auth:8080"
  PROFILE_INTERNAL_URL: "http://profile:8080"
  STORAGE_ENDPOINT: "minio:9000"
  STORAGE_PUBLIC_BASE_URL: "http://snooker.local/snooker-profiles"
  STORAGE_BUCKET_NAME: "snooker-profiles"
  STORAGE_REGION: "us-east-1"
  STORAGE_USE_SSL: "false"
  PROFILE_MAX_PHOTO_BYTES: "2097152"
  NATS_URL: "nats://nats:4222"
  GAME_OWNER_DISCONNECT_TIMEOUT_SECONDS: "10"
  MINIO_API_CORS_ALLOW_ORIGIN: "http://snooker.local"
