apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-admin
  namespace: snooker
  labels:
    app.kubernetes.io/name: headlamp-admin
    app.kubernetes.io/part-of: snooker
---
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-admin-token
  namespace: snooker
  annotations:
    kubernetes.io/service-account.name: headlamp-admin
  labels:
    app.kubernetes.io/name: headlamp-admin
    app.kubernetes.io/part-of: snooker
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin-binding
  labels:
    app.kubernetes.io/name: headlamp-admin
    app.kubernetes.io/part-of: snooker
subjects:
  - kind: ServiceAccount
    name: headlamp-admin
    namespace: snooker
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp
  namespace: snooker
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/part-of: snooker
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: headlamp.maiconda.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headlamp
                port:
                  number: 80
