apiVersion: v1
kind: ServiceAccount
metadata:
  name: snooker-app
  namespace: snooker
  labels:
    app.kubernetes.io/name: snooker
    app.kubernetes.io/part-of: snooker
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snooker-data
  namespace: snooker
  labels:
    app.kubernetes.io/name: snooker-data
    app.kubernetes.io/part-of: snooker
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snooker-job
  namespace: snooker
  labels:
    app.kubernetes.io/name: snooker-job
    app.kubernetes.io/part-of: snooker
automountServiceAccountToken: false
